// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AdminaddingfoodTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void adminaddingfood() {
    driver.get("https://gymprogress.lukakordic.me/admin");
    driver.manage().window().setSize(new Dimension(1437, 916));
    {
      WebElement element = driver.findElement(By.linkText("Food"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Food")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".bg-black:nth-child(1)")).click();
    driver.findElement(By.id(":r2:-form-item")).click();
    driver.findElement(By.id(":r2:-form-item")).sendKeys("Test");
    driver.findElement(By.id(":r3:-form-item")).click();
    driver.findElement(By.id(":r3:-form-item")).sendKeys("0100");
    driver.findElement(By.id(":r4:-form-item")).click();
    driver.findElement(By.id(":r4:-form-item")).click();
    {
      WebElement element = driver.findElement(By.id(":r4:-form-item"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id(":r4:-form-item")).sendKeys("200");
    driver.findElement(By.id(":r5:-form-item")).sendKeys("300");
    driver.findElement(By.id(":r6:-form-item")).sendKeys("400");
    driver.findElement(By.id(":r7:-form-item")).sendKeys("gram");
    driver.findElement(By.id(":r8:-form-item")).sendKeys("2");
    driver.findElement(By.cssSelector(".h-9")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".h-9"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".h-9")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".h-9"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Admin"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Workout Plans"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Food")).click();
    driver.close();
  }
}
