// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginwrongusernameandpasswordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginwrongusernameandpassword() {
    driver.get("https://gymprogress.lukakordic.me/");
    driver.manage().window().setSize(new Dimension(1609, 1106));
    driver.findElement(By.cssSelector(".max-xl\\3Apt-\\[4rem\\]")).click();
    driver.findElement(By.linkText("Go to the app")).click();
    driver.findElement(By.id(":r0:-form-item")).click();
    driver.findElement(By.id(":r0:-form-item")).sendKeys("špoqwelaskd");
    driver.findElement(By.name("password")).sendKeys("špqowdas");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.close();
  }
}
