# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
    paths:
      - "IzvorniKod/backend/**"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Generate application.properties
        run: |
            echo "spring.application.name=gym-fitness-tracker
            spring.datasource.url=${{ secrets.DB_URL }}
            spring.datasource.username=${{ secrets.DB_USERNAME }}
            spring.datasource.password=${{ secrets.DB_PASSWORD }}
            spring.datasource.driver-class-name=org.postgresql.Driver
            spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
            spring.jpa.hibernate.ddl-auto=update
            
            # Email configuration
            spring.mail.host=smtp.gmail.com
            spring.mail.port=587
            spring.mail.username=${{ secrets.MAIL_USERNAME }}
            spring.mail.password=${{ secrets.MAIL_PWD }}
            spring.mail.properties.mail.smtp.auth=true
            spring.mail.properties.mail.smtp.starttls.enable=true
            
            #AWS Configuration
            cloud.aws.credentials.accessKey=${{ secrets.AWS_ACCESS_KEY }}
            cloud.aws.credentials.secretKey=${{ secrets.AWS_SECRECT_KEY }}
            cloud.aws.region.static=${{ secrets.AWS_REGION }}
            cloud.aws.s3.bucket=${{ secrets.AWS_S3_BUCKET }}
            " > IzvorniKod/backend/src/main/resources/application.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn -B package --file IzvorniKod/backend/pom.xml

      - name: Execute Jar File
        run: sudo kill $(sudo lsof -t -i:8080) & sudo java -jar /home/admin/actions-runner/_work/CodeMonkeys/CodeMonkeys/IzvorniKod/backend/target/gym-fitness-tracker-0.0.1-SNAPSHOT.jar &

      - name: Edit permissions
        run: sudo chmod -R 777 /home/admin/actions-runner/_work/CodeMonkeys
