# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
    paths:
      - "IzvorniKod/backend/**"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Update db url
        run: sed -i 's|<db_url>|${{ secrets.DB_URL }}|' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update db username
        run: sed -i 's/<db_username>/${{ secrets.DB_USERNAME }}/' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update db password
        run: sed -i 's/<db_password>/${{ secrets.DB_PASSWORD }}/' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update google client ID
        run: sed -i 's/<google_id>/${{ secrets.GOOGLE_CLIENT_ID }}/' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update google client secret
        run: sed -i 's/<google_secret>/${{ secrets.GOOGLE_CLIENT_SECRET }}/' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update facebook client ID
        run: sed -i 's/<facebook_secret>/${{ secrets.FACEBOOK_CLIENT_ID }}/' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update facebook client secret
        run: sed -i 's/<facebook_secret>/${{ secrets.FACEBOOK_CLIENT_SECRET }}/' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update mail username
        run: sed -i 's/<mail_username>/${{ secrets.MAIL_USERNAME }}/' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update aws access key
        run: sed -i 's/<aws_access>/${{ secrets.AWS_ACCESS_KEY }}/' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update aws secret key
        run: sed -i 's|<aws_secret>|${{ secrets.AWS_SECRECT_KEY }}|' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update region
        run: sed -i 's/<aws_region>/${{ secrets.AWS_REGION }}/' IzvorniKod/backend/src/main/resources/application.properties
      - name: Update mail password
        run: sed -i 's/<aws_bucket>/${{ secrets.AWS_S3_BUCKET }}/' IzvorniKod/backend/src/main/resources/application.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn -B package --file IzvorniKod/backend/pom.xml

      - name: Execute Jar File
        run: sudo kill $(sudo lsof -t -i:8080) & sudo java -jar /home/admin/actions-runner/_work/CodeMonkeys/CodeMonkeys/IzvorniKod/backend/target/gym-fitness-tracker-0.0.1-SNAPSHOT.jar &

      - name: Edit permissions
        run: sudo chmod -R 777 /home/admin/actions-runner/_work/CodeMonkeys
