# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
    paths:
      - "IzvorniKod/backend/**"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Create .env file
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" > IzvorniKod/backend/src/main/resources/.env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> IzvorniKod/backend/src/main/resources/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> IzvorniKod/backend/src/main/resources/.env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> IzvorniKod/backend/src/main/resources/.env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> IzvorniKod/backend/src/main/resources/.env
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> IzvorniKod/backend/src/main/resources/.env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRECT_KEY }}" >> IzvorniKod/backend/src/main/resources/.env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> IzvorniKod/backend/src/main/resources/.env
          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" >> IzvorniKod/backend/src/main/resources/.env

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn -B package --file IzvorniKod/backend/pom.xml

      - name: Execute Jar File
        run: sudo kill $(sudo lsof -t -i:8080) & sudo java -jar /home/admin/actions-runner/_work/CodeMonkeys/CodeMonkeys/IzvorniKod/backend/target/gym-fitness-tracker-0.0.1-SNAPSHOT.jar &

      - name: Edit permissions
        run: sudo chmod -R 777 /home/admin/actions-runner/_work/CodeMonkeys
