name: Node.js CI

on:
  push:
    branches: ["dev"]
    paths:
      - "IzvorniKod/frontend/**"
  pull_request:
    branches: ["dev"]
    paths:
      - "IzvorniKod/frontend/**"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.16.0]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Change Directory
        run: cd IzvorniKod/frontend
      - name: Create .env file
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          echo "FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}" >> .env
          echo "FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}" >> .env
          # Add more environment variables as needed
      - run: npm ci
      - run: npm run build --if-present
